---
# handlers file for update-workernodes

# Stänger av schemaläggning på noden
- name: Disable scheduling on node
  ansible.builtin.command:
    cmd: kubectl cordon {{ inventory_hostname }}
  delegate_to: localhost
  become: false

# Tar bort alla poddar på från noden
- name: Drain pods on node
  ansible.builtin.command:
    cmd: kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data
  delegate_to: localhost
  become: false

# Startar om noden
- name: Reboot the server
  ansible.builtin.reboot:
    reboot_timeout: 3600 # Sätter timeout på 60 minuter för att säkerställa att det fungerar på långsamma noder också.

# Enablar schemaläggning på noden efter omstart
- name: Enable scheduling on node
  ansible.builtin.command:
    cmd: kubectl uncordon {{ inventory_hostname }}
  delegate_to: localhost
  become: false
