---
# tasks file for install-calico

# Installerar nätverksplugin till klustret (Calico)
- name: Install Calico
  ansible.builtin.command:
    kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  args:
    creates: /etc/cni/net.d/calico-kubeconfig
  become: false
