---
# handlers file for install-containerd

# Startar om Containerd efter uppdatering av config
- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
