---
- name: Install Monitoring
  hosts: masternodes
  become: true
  vars_files:
    - vault.yaml # Fil med krypterade lösenord
    - common.yaml # Fil med variabler som används i koden

  vars: 
    ansible_become_pass: "{{ become_password }}"

  tasks:

    # Konfigurerar upp namespaces monitoring
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: monitoring
        kubeconfig: "{{ kubeconfig }}"

    # Laddar ner och installerar Helm (Pakethanterare för kubernetes)
    - name: Download and install Helm
      ansible.builtin.shell: |
        curl -fsSL https://get.helm.sh/helm-v3.10.0-linux-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm
        rm -rf linux-amd64 helm.tar.gz
      args:
        creates: /usr/local/bin/helm

    - name: Add prometheus Helm repository
      ansible.builtin.command:
        cmd: "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts"
      become_user: "{{ ansible_user }}"

    - name: Add Grafana Helm repository
      ansible.builtin.command:
        cmd: "helm repo add grafana https://grafana.github.io/helm-charts" 
      become_user: "{{ ansible_user }}"

    - name: Update helm repository
      ansible.builtin.command:
        cmd: helm repo update
      become_user: "{{ ansible_user }}"

    - name: Copy smtp-values.yaml to remote node
      ansible.builtin.copy:
        src: smtp-values.yaml
        dest: /home/{{ ansible_user }}/smtp-values.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'


    - name: Install prometheus-community/kube-prometheus-stack
      ansible.builtin.command:
        cmd: "helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --values /home/{{ ansible_user }}/smtp-values.yaml --set grafana.adminPassword=Linux4Ever"      
      become_user: "{{ ansible_user }}"

    # Screen används för att köra port forward i separat terminal
    - name: Ensure screen is installed
      ansible.builtin.package:
        name: screen
        state: present

    # Portforward från grafana -> masternoden
    - name: Port-forward in detached mode using async
      ansible.builtin.command:
        cmd: screen -dmS portforward kubectl port-forward svc/prometheus-grafana 3000:80 -n monitoring
      become_user: "{{ ansible_user }}"
      async: 3600  # Time in seconds (1 hour)
      poll: 5  # Don't wait for the command to finish

- name: Setup SSH localhost
  hosts: localhost
  become: true
  vars_files:
    - vault.yaml

  vars: 
    ansible_become_pass: "{{ become_password }}"

  tasks:

    # Screen används för att öppna ssh-anslutning i en separat terminal
    - name: Ensure screen is installed
      ansible.builtin.package:
        name: screen
        state: present
    
    # Skapar SSH-anslutning mellan localhost:3000 -> masternode:3000
    - name: Setup SSH connection to Grafana
      ansible.builtin.command:
        cmd: screen -dmS ssh-connection ssh -N -L 3000:localhost:3000 {{ hostvars[groups['masternodes'][0]]['ansible_user'] }}@10.0.2.18
      become_user: administrator




