---

- name: Update servers
  hosts: all
  become: true
  vars_files:
    - vault.yaml

  vars: 
    ansible_become_pass: "{{ become_password }}"
  
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

# Play 1: Konfigurering av alla noder
- name: Install Kubernetes on all nodes
  hosts: all
  become: true
  vars_files:
    - vault.yaml

  vars: 
    ansible_become_pass: "{{ become_password }}"

  tasks:

# Installerar beroenden för installationen
    - name: Install required packages (apt-transport-https, ca-certificates, curl, gpg)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present
        update_cache: yes

    - name: Disable swapoff
      ansible.builtin.shell: "swapoff -a"

# Kommenterar ut swap ur fstab (Rekommenderas av Kubernetes)
    - name: Comment out swap entry in /etc/fstab to disable swap
      ansible.builtin.lineinfile:
        path: "/etc/fstab"
        line: ''
        regexp: '^/swap.img*'

# Installerar Docker Engine
    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker.io
        state: present
        update_cache: yes

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Laddar ner nyckel för att komma åt repository
    - name: Download the Kubernetes GPG signing key
      ansible.builtin.shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
      args:  
        creates: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
  
    # Lägger till Kubernetes repository      
    - name: Add the Kubernetes apt repository for v1.31
      ansible.builtin.shell: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"
  
    # Uppdaterar cachen efter tillägg av Kubernetes repository
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    # Installerar administrationsverktyg för klustret
    - name: Install Kubernetes packages (kubeadm, kubelet, kubectl)
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

# Play 2: Konfigurering av Masternodes
- name: Setup masternodes
  hosts: masternodes
  become: true
  vars_files:
    - vault.yaml

  vars: 
    ansible_become_pass: "{{ become_password }}"
    user: "administrator"
  tasks:
    
    # Initierar klustret
    - name: Initialize Cluster
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: kubeadm_output
      args:
        creates: /etc/kubernetes/kubelet.conf
  
    # Skapar Kube directory på masternode
    - name: Create Kube directory
      ansible.builtin.command:
        cmd: mkdir -p /home/administrator/.kube
    # Kopierar in configfil till kube directory
    - name: Copy config to kube directory
      ansible.builtin.command:
        cmd: cp -i /etc/kubernetes/admin.conf /home/administrator/.kube/config
      args:
        creates: /home/administrator/.kube/config
    
    # Ändrar rättigheter på configfil
    - name: Change config permission
      ansible.builtin.shell: |
        chown {{ user }}:{{ user }} /home/administrator/.kube/config

    # Skapar join token till klustret
    - name: Create kubeadm token
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: join_token

    # Kopierar token till kontrollnoden
    - name: Save the generated token to a file
      ansible.builtin.copy:
        content: "{{ join_token.stdout }}"
        dest: /tmp/join_token
      delegate_to: localhost

      # Installera nätverksplugin Calico
    - name: Install Calico
      ansible.builtin.command:
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      become_user: administrator

# Play 3: Joinar workernodes till klustret
- name: Join workers to cluster
  hosts: workernodes
  become: true
  vars_files:
    - vault.yaml
    
  vars: 
    ansible_become_pass: "{{ become_password }}"
  tasks:
    
    # Kopierar över Join_token till noderna
    - name: Create Join_token file on workernodes
      ansible.builtin.copy:
        src: /tmp/join_token
        dest: /tmp/join_token.sh
        mode: '0755'

    # Kör Join_token script
    - name: Join workers to cluster
      ansible.builtin.shell:
        cmd: /tmp/join_token.sh
      args:
        creates: /etc/kubernetes/kubelet.conf



    




