---
# tasks file for install-helm

- name: Download Helm tarball
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.10.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    mode: '0644'
    force: false

- name: Extract Helm tarball
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
    remote_src: true

- name: Copy Helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: true
  become: true
