apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-webserver-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ts-webserver-01
  template:
    metadata:
      labels:
        app: ts-webserver-01
    spec:
      containers:
        - name: ts-webserver-01
          image: nginx:latest
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-ts-webserver-01
spec:
  type: LoadBalancer  # Skapar Loadbalancer
  ports:
    - port: 80        # Port 80:80   
      targetPort: 80
  selector:
    app: ts-webserver-01 # Binder den till ts-webserver-01
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ts-webserver-01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ts-webserver-01
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
