---
# tasks file for initialize-cluster

# Initierar klustret med IP-range för att match med Calico:s nätverksplugin
- name: Initialize cluster
  ansible.builtin.command:
    cmd: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Create Kube directory recursively
  ansible.builtin.file:
    path: "{{ kubedirectory }}"
    state: directory
    mode: '0755'
    # recurse: true # Tillåter rekursiv skapande av mappar
    force: false

# Kopierar över kubelet config från admin.conf
- name: Copy config to kube directory
  ansible.builtin.command:
    cmd: cp -i /etc/kubernetes/admin.conf {{ kubeconfig }}
  args:
    creates: "{{ kubeconfig }}"

# Ändrar rättigheter för configfilen (Gör den åtkomlig för användarkontot)
- name: Change config ownership
  ansible.builtin.file:
    path: "{{ kubeconfig }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'  # Säkerställ att endast användaren kan läsa och skriva filen
