---
# tasks file for portforward-grafana

# Portforward från grafana -> masternoden
- name: Port-forward in detached mode using async
  ansible.builtin.command:
    cmd: screen -dmS portforward kubectl port-forward svc/prometheus-grafana 3000:80 -n monitoring
  become_user: administrator
  async: 3600  # Time in seconds (1 hour)
  poll: 1  # Don't wait for the command to finish
