---
# tasks file for update-workernodes

# Uppdatera paketen
- name: Update apt package index (Ubuntu/Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

# Uppgradera paketen
- name: Upgrade all packages (Ubuntu/Debian)
  ansible.builtin.apt:
    upgrade: safe

  notify:
    - Disable scheduling on node
    - Drain pods on node
    - Reboot the server
    - Enable scheduling on node
