---
# tasks file for update-workernodes

# Uppdatera paketen
- name: Update apt package index (Ubuntu/Debian)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    
# Uppgradera paketen
- name: Upgrade all packages (Ubuntu/Debian)
  ansible.builtin.apt:
    upgrade: safe
    
# Stänger av schemaläggningen på noden
- name: Disable schudueling on node
  ansible.builtin.shell: |
    kubectl cordon {{ inventory_hostname }}
  delegate_to: localhost
  become_user: "{{ ansible_user }}"

# Tar bort alla poddar på från noden
- name: Drain pods on node
  ansible.builtin.shell: |
    kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data
  delegate_to: localhost
  become_user: "{{ ansible_user }}"

# Startar om noden
- name: Reboot the server
  ansible.builtin.reboot:
    reboot_timeout: 3600 #Sätter timeout på 60 minuter för att säkerställa att det fungerar på långsamma noder också.

# Enablar schemaläggning på noden efter omstart
- name: Enable schudueling on node
  ansible.builtin.shell: |
    kubectl uncordon {{ inventory_hostname }} 
  delegate_to: localhost
  become_user: "{{ ansible_user }}"
