---
# tasks file for install-python3

# Installera Python3 och pip (Behövs för att kunna installera kubernetes-paket)
- name: Install Python 3 and pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

# Install Kubernetes Python client
- name: Install Kubernetes Python client
  ansible.builtin.pip:
    name: kubernetes
    break_system_packages: true
    state: present