---
# tasks file for install-prometheus-stack

- name: Add Prometheus Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present
  become: false
  register: prometheus_stack

- name: Add Grafana Helm repository
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
    state: present
  become: false
  register: prometheus_stack

- name: Install Prometheus kube-prometheus-stack
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    create_namespace: true
    values:
      grafana:
        adminPassword: "{{ grafana_password }}"
    state: present
  become: false
  register: prometheus_stack
  notify: Wait for monitoring pods to get ready # Notifiera handlern om förändringar sker
