---
# tasks file for install-kured

- name: Install Kured
  ansible.builtin.shell: |
    latest=$(curl -s https://api.github.com/repos/kubereboot/kured/releases | jq -r '.[0].tag_name') && kubectl apply -f "https://github.com/kubereboot/kured/releases/download/$latest/kured-$latest-dockerhub.yaml"
  become: false
