---
# tasks file for install-kubectl

# Installerar beroenden för kubectl
- name: Install required packages (apt-transport-https, ca-certificates, curl, gpg)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - lsb-release
      - gnupg

    state: present
    update_cache: true

# Lägger till nyckel för Kubernetes repository
- name: Add Kubernetes repository key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true

# Lägger till Kubernetes repository
- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
    state: present
    update_cache: true

# Installerar verktyg för Kubernetes
- name: Install kubectl on localhost
  ansible.builtin.apt:
    name:
      - kubectl
    state: present

# Ser till att /.kube foldern existerar på localhost
- name: Create kube directory
  ansible.builtin.file:
    path: /home/administrator/.kube/
    state: directory
    mode: '0755'
