---
# tasks file for configure-node-labels
- name: Label a Kubernetes node
  ansible.builtin.command:
    cmd: kubectl label nodes {{ item }} node-role.kubernetes.io/worker= --kubeconfig=/{{ kubeconfig }}
  loop: "{{ groups['workernodes'] }}"
  ignore_errors: true  # Ignorera fel om noden inte är online
