---
# handlers file for install-prometheus-stack
- name: Wait for monitoring pods to get ready # noqa: ansible-lint:no-changed-when
  ansible.builtin.command:
    cmd: "kubectl wait --for=condition=Ready pods --all -n monitoring --timeout=300s"
  become: false
  when: prometheus_stack.changed  # Vänta endast om det skedde en förändring
