---
# PLAY 1: ALL NODES
- name: Setup kubernetes nodes
  hosts: cluster
  become: true
  vars_files:
    - vault.yaml  # Krypterad fil som innehåller secrets
    - common.yaml # Variabler som används för dynamisk playbook

  vars:
    ansible_become_pass: "{{ become_password }}"

  roles:
    - install-containerd # Installerar Containerd
    - install-kubernetes # Installerar Kubernetes
    - install-python3    # Installerar Python3 och Python3-pip (För att kunna köra Kubernetes-moduler till Ansible)

# PLAY 2: MASTERNODES
- name: Setup kubernetes Masternode
  hosts: masternodes
  become: true
  vars_files:
    - vault.yaml  # Krypterad fil som innehåller secrets
    - common.yaml # Variabler som används för dynamisk playbook
  vars:
    ansible_become_pass: "{{ become_password }}"

  roles:
    - initialize-cluster            # Initialiserar klustret
    - install-calico                # Installerar nätverksplugin (Calico) (IP-range 192.168.0.0/16)
    - create-join-token             # Skapar jointoken för workernodes
    - create-kubeconfig-localhost   # Skapar kubeconfig för localhost

# PLAY 3: WORKERNODES
- name: Setup Kubernetes workernodes
  hosts: workernodes
  become: true
  vars_files:
    - vault.yaml  # Krypterad fil som innehåller secrets
    - common.yaml # Variabler som används för dynamisk playbook
    
  vars: 
    ansible_become_pass: "{{ become_password }}"
    
  roles: 
    - join-cluster # Workernodes joinar klustret


# PLAY 4: LOCALHOST
- name: Setup kubernetes localhost
  hosts: localhost
  become: true
  vars_files:

    - vault.yaml  # Krypterad fil som innehåller secrets
    - common.yaml # Variabler som används för dynamisk playbook
    
  vars:
   
    ansible_become_pass: "{{ become_password }}"
    
    roles:

      - install-kubectl # Installerar kubectl (För att kunna styra klustret utifrån)
      - install-python3 # Installerar Python3 och Python3-pip (För att kunna köra Kubernetes-moduler till Ansible)
