---
# PLAY 1:
- name: Update nodes
  hosts: workernodes
  become: true
  serial: 1
  vars_files:
    - vault/ts-vault.yaml   # Krypterad fil som innehåller secrets
    - vars/common.yaml      # Variabler som används för dynamisk playbook

  vars:
    ansible_become_pass: "{{ become_password }}"

  roles:
    - update-workernodes

# PLAY 2:
- name: Portforward after update
  hosts: localhost
  become: true
  vars_files:
    - vault/ts-vault.yaml   # Krypterad fil som innehåller secrets
    - vars/common.yaml      # Variabler som används för dynamisk playbook

  vars:
    ansible_become_pass: "{{ become_password }}"

  roles:
    - portforward-grafana     # STARTAR OM PORTFORWARDING EFTER RESTART
    - portforward-prometheus  # STARTAR OM PORTFORWARDING EFTER RESTART
