---
# tasks file for install-containerd


# Installerar beroenden för installation av Containerd och Kubernetes
- name: Install required packages (apt-transport-https, ca-certificates, curl, gpg)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - lsb-release
      - gnupg

    state: present
    update_cache: yes

# Stänger av swapoff
- name: Disable swapoff
  ansible.builtin.shell: "swapoff -a"
  
# Tar bort swapoff från FSTAB
- name: Comment out swap entry in /etc/fstab to disable swap
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: ''
    regexp: '^/swap.img*'
    state: absent # Ser till att raden inte existerar

# Laddar till Dockers repository nyckel (Samma som för Containerd)
- name: Add Docker GPG key for repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
# Lägger till repository för Containerd
- name: Add Docker repository for containerd
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    
# Installerar Containerd
- name: Install Containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    state: present
    update_cache: yes

# Lägger till kernel moduler för nätverk
- name: Create /etc/modules-load.d/k8s.conf to load overlay and br_netfilter modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'


- name: Load overlay module
  ansible.builtin.modprobe:
    name: overlay


- name: Load br_netfilter module
  ansible.builtin.modprobe:
    name: br_netfilter

- name: Create /etc/sysctl.d/k8s.conf for Kubernetes settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings
  ansible.builtin.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes

- name: Apply sysctl settings for bridge-nf-call-ip6tables
  ansible.builtin.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    reload: yes

- name: Apply sysctl settings for ip_forward
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

# Skapar default configfil för Containerd (Config.toml)
- name: Create default kubernetes config
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  register: containerd_changes

# Ändrar värdet på SystemCgroup i configfilen
- name: Change SystemCgroup in config
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup = false'
    line: "            SystemdCgroup = true"
    state: present

# Ändrar värdet för att tillåta TCP-anslutningar (Config.toml)
- name: Enable TCP service
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*disable_tcp_service = true'
    line: "    disable_tcp_service = false"
    state: present

# Startar om Containerd efter uppdatering av config
- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
